#!/bin/sh
lock() {
    B='#00000000'  # blank
    C='#ffffff22'  # clear ish
    D='#ff00ffcc'  # default
    T='#ee00eeee'  # text
    W='#880000bb'  # wrong
    V='#bb00bbbb'  # verifying

    i3lock        \
        --insidevercolor=$C   \
        --ringvercolor=$V     \
        \
        --insidewrongcolor=$C \
        --ringwrongcolor=$W   \
        \
        --insidecolor=$B      \
        --ringcolor=$D        \
        --linecolor=$B        \
        --separatorcolor=$D   \
        \
        --textcolor=$T        \
        --timecolor=$T        \
        --datecolor=$T        \
        --keyhlcolor=$W       \
        --bshlcolor=$W        \
        \
        --screen 0            \
        --blur 5              \
        --clock               \
        --indicator           \
        --timestr="%H:%M:%S"  \
        --datestr="%A, %m %Y" 
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        # There's some memory leak at the present (2018-02-22)
        # lock
        systemctl suspend
        ;;
    hibernate)
        # lock
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
